@HostAddress = http://localhost:1323/api/v1

#for test with container
#cmd docker run -p 10170:1323 -e DB_CONN="host=<Your_IP> port=5432 user=root password=password dbname=wallet sslmode=disable" wallerservice:1.0.0

#@HostAddress = http://localhost:10170/api/v1

### Get Wallets
GET {{HostAddress}}/wallets


### Get Wallet Query Param (wallet_type)
GET {{HostAddress}}/wallets?wallet_type=Savings

### Create Wallet
POST {{HostAddress}}/wallets
Content-Type: application/json

{
    "user_id": 99,
    "user_name": "PingkungA",
    "wallet_name": "PingkungA Wallet",
    "wallet_type": "Savings",
    "balance": 1000
}

### Update Wallet
PUT {{HostAddress}}/wallets
Content-Type: application/json

{
    "id": 7,
    "user_id": 99,
    "user_name": "PingkungA Updated",
    "wallet_name": "PingkungA Wallet",
    "wallet_type": "Savings",
    "balance": 1500
}

### Delete Wallet
DELETE {{HostAddress}}/users/99/wallets

### Get Wallets by User ID
GET {{HostAddress}}/users/1/wallets
